name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha de commits
        uses: Platane/snk@v3
        with:
          github_user_name: abimaeltech
          outputs: |
            ./dist/github-contribution-grid-snake.svg
            ./dist/github-contribution-grid-snake-dark.svg

      - name: Criar branch `output` e enviar arquivos
        run: |
          mkdir -p output
          mv dist/* output/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan output
          git --work-tree output add --all
          git --work-tree output commit -m "Atualiza cobrinha de commits"
          git push origin output --force
